# Generated by Django 4.2 on 2023-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('content', models.CharField(blank=True, max_length=128, null=True)),
                ('prince', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
    ]
